name: Publish
on:
    push:
        tags:
            - '*'
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
            - uses: actions/setup-node@ab72c7e7eba0eaa11f8cab0f5679243900c2cac9
              with:
                node-version: '24'
                registry-url: 'https://registry.npmjs.org'
            - name: Setup Bun
              uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6
            - name: Install dependencies
              run: bun install
            - name: Build and pack
              run: bun run build-lib && bun pm pack
            - name: Create release
              uses: softprops/action-gh-release@4dd30955cca228da305ffee6fbc3fc1f95d447c2
              with:
                draft: false
                files: ilias-client-*.tgz
            - name: Publish to npm
              run: npm publish --provenance ./ilias-client-*.tgz
